# Field extraction patterns and validation rules
timestamp:
  patterns:
    - '^(\d{4} \w{3}\s+\d+\s+\d{2}:\d{2}:\d{2}\.\d{3})'
  validation:
    required: true
    format: "datetime"
  description: "Message timestamp"

direction:
  patterns:
    - 'LTE NAS.*Plain OTA.*(Incoming|Outgoing).*Message.*--'
    - 'LTE NAS.*State'
    - 'LTE NAS.*Bearer Context.*State'
    - 'NR5G NAS.*Plain.*Message.*Container'
    - 'NR5G NAS.*State'
    - 'NR5G NAS.*Service Request'
    - 'NR5G NAS.*NSSAI Info'
  validation:
    required: true
    allowed_values: ["Incoming", "Outgoing", "State"]
  description: "Message direction (UE-to-Network, Network-to-UE, or State)"

message_type:
  patterns:
    - 'LTE NAS.*(?:Plain )?OTA.*(Incoming|Outgoing).*Message.*--\s*(.+?)(?:\s+Msg)?$'
    - 'LTE NAS.*State.*--\s*(.+?)(?:\s+Msg)?$'
    - 'LTE NAS.*Bearer Context.*State.*--\s*(.+?)(?:\s+Msg)?$'
    - 'LTE NAS.*Bearer Context.*Info.*--\s*(.+?)(?:\s+Msg)?$'
    - 'NR5G NAS.*Plain Message Container.*msg_type = \d+.*?\\((.+?)\\)'
    - 'NR5G NAS.*State.*--\s*(.+?)(?:\s+Msg)?$'
    - 'NR5G NAS.*Service Request'
    - 'NR5G NAS.*NSSAI Info'
  validation:
    required: true
  description: "Type of NAS message"

# 5G NR Specific Fields
amf_region_id:
  patterns:
    - 'AMF_Region_ID = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "AMF Region ID"

amf_set_id:
  patterns:
    - 'AMF_SET_ID = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "AMF Set ID"

amf_pointer:
  patterns:
    - 'AMF_Pointer = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "AMF Pointer"

fiveg_tmsi:
  patterns:
    - '_5g_tmsi\\[0\\] = (\\d+).*_5g_tmsi\\[1\\] = (\\d+).*_5g_tmsi\\[2\\] = (\\d+).*_5g_tmsi\\[3\\] = (\\d+)'
  validation:
    required: false
  description: "5G TMSI (complete array)"

registration_type:
  patterns:
    - '_5gs_reg_type = (\\d+).*?\\((.*?)\\)'
  validation:
    required: false
  description: "5GS Registration Type"

mm5g_state:
  patterns:
    - 'MM5G State = ([A-Z_]+)'
  validation:
    required: false
  description: "MM5G State"

mm5g_substate:
  patterns:
    - 'Mm5g.*Substate = ([A-Z_]+)'
  validation:
    required: false
  description: "MM5G Substate"

plmn_identity:
  patterns:
    - 'Identity = \\{ ([0-9x, ]+) \\}'
  validation:
    required: false
  description: "PLMN Identity"

nssai_sst:
  patterns:
    - 'SST = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "NSSAI SST"

nssai_sd:
  patterns:
    - 'SD.*Octets = \\{ ([0-9, ]+) \\}'
  validation:
    required: false
  description: "NSSAI SD"

# 5G Security Algorithms
ea0_5g:
  patterns:
    - 'EA0_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Encryption Algorithm 0"

ea1_128_5g:
  patterns:
    - 'EA1_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Encryption Algorithm 1-128"

ea2_128_5g:
  patterns:
    - 'EA2_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Encryption Algorithm 2-128"

ea3_128_5g:
  patterns:
    - 'EA3_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Encryption Algorithm 3-128"

ia1_128_5g:
  patterns:
    - 'IA1_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Integrity Algorithm 1-128"

ia2_128_5g:
  patterns:
    - 'IA2_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Integrity Algorithm 2-128"

ia3_128_5g:
  patterns:
    - 'IA3_128_5G = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5G Integrity Algorithm 3-128"

# 5G Capabilities
fivegmm_cap_len:
  patterns:
    - '_5GMM_CAP_Len = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5GMM Capability Length"

fivegc_cap:
  patterns:
    - '_5GC = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "5GC Capability"

s1_mode_cap:
  patterns:
    - 'S1_mode = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "S1 Mode Capability"

ho_attach_cap:
  patterns:
    - 'HO_attach = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Handover Attach Capability"

# Network Selection
net_selection_mode:
  patterns:
    - 'Net Selection Mode = ([A-Z_]+)'
  validation:
    required: false
  description: "Network Selection Mode"

req_type:
  patterns:
    - 'Req Type = ([A-Z_]+)'
  validation:
    required: false
  description: "Request Type"

# Enhanced QCI for 5G NR
qci:
  patterns:
    - 'qci = (\\d+)'
  validation:
    required: false
    data_type: "integer"
    range: [1, 255]  # Extended range for 5G NR
  description: "QoS Class Identifier"

bearer_id:
  patterns:
    - 'Bearer ID = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "EPS Bearer ID"

apn:
  patterns:
    - 'acc_pt_name_val\\[\\d+\\] = \\d+ \\(.+\\) \\((.+)\\)'
  validation:
    required: false
    min_length: 1
  description: "Access Point Name"

ipv4:
  patterns:
    - 'ipv4_addr = \\d+ \\(0x[0-9a-fA-F]+\\) \\(([ 0-9\\.]+)\\)'
  validation:
    required: false
    format: "ipv4"
  description: "IPv4 address"

mcc:
  patterns:
    - 'mcc_1 = (\\d+).*mcc_2 = (\\d+).*mcc_3 = (\\d+)'
  validation:
    required: false
    data_type: "string"
    length: 3
  description: "Mobile Country Code"

mnc:
  patterns:
    - 'mnc_1 = (\\d+).*mnc_2 = (\\d+).*mnc_3 = (\\d+)'
  validation:
    required: false
    data_type: "string"
    length: 3
  description: "Mobile Network Code"

guti:
  patterns:
    - 'id_type = \\d+.*GUTI'
  validation:
    required: false
    allowed_values: ["yes", ""]
  description: "Globally Unique Temporary Identifier"

mme_group_id:
  patterns:
    - 'MME_group_id = (\\d+) \\(0x[0-9a-fA-F]+\\\\)'
  validation:
    required: false
    data_type: "integer"
  description: "MME Group ID"

mme_code:
  patterns:
    - 'MME_code = (\\d+) \\(0x[0-9a-fA-F]+\\\\)'
  validation:
    required: false
    data_type: "integer"
  description: "MME Code"

tmsi:
  patterns:
    - 'm_tmsi = (\\d+) \\(0x[0-9a-fA-F]+\\\\)'
  validation:
    required: false
    data_type: "integer"
  description: "Temporary Mobile Subscriber Identity"

nas_key_set_id:
  patterns:
    - 'nas_key_set_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "NAS Key Set Identifier"

att_type:
  patterns:
    - 'att_type = (\\d+).*?\\((.*?)\\)'
  validation:
    required: false
  description: "Attach Type"

tsc:
  patterns:
    - 'tsc = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Type of Security Context"

eea:
  patterns:
    - '(EEA\\d+(_128)?) = (\\d+)'
  validation:
    required: false
  description: "EPS Encryption Algorithms"

eia:
  patterns:
    - '(EIA\\d+(_128)?) = (\\d+)'
  validation:
    required: false
  description: "EPS Integrity Algorithms"

uea:
  patterns:
    - '(UEA\\d+) = (\\d+)'
  validation:
    required: false
  description: "UMTS Encryption Algorithms"

# Enhanced fields for container analysis
subscription_id:
  patterns:
    - 'subscription_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Subscription ID"

version:
  patterns:
    - 'version = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Protocol version"

trans_id:
  patterns:
    - 'trans_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Transaction ID"

emm_state:
  patterns:
    - 'emm_state = ([A-Z_]+)'
  validation:
    required: false
  description: "EMM state"

emm_sub_state:
  patterns:
    - 'emm_sub_state = ([A-Z_]+)'
  validation:
    required: false
  description: "EMM sub-state"

procedure_state:
  patterns:
    - 'procedure_state = ([A-Z_]+)'
  validation:
    required: false
  description: "Procedure state"

pti:
  patterns:
    - 'pti = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Procedure Transaction Identity"

sdf_id:
  patterns:
    - 'sdf_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Service Data Flow ID"

bearer_state:
  patterns:
    - 'bearer_state = ([A-Z_ ]+)'
  validation:
    required: false
  description: "Bearer state"

connection_id:
  patterns:
    - 'connection_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Connection ID"

rb_id:
  patterns:
    - 'rb_id = (\\d+)'
  validation:
    required: false
    data_type: "integer"
  description: "Radio Bearer ID" 